version: '3'
services:
  petclinic:
    image: springpetclinic_petclinic
    ports:
      - 9500:8080
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
